services:
  # --- ENTORNO APACHE ---
  apache:
    profiles: ["apache"]
    build:
      context: .
      dockerfile: apache.Dockerfile
    image: localhost/${PROJECT_NAME}_apache:latest
    container_name: ${PROJECT_NAME}_apache
    userns_mode: "keep-id"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./:/var/www/html:Z
      - ./certs:/etc/apache2/certs:Z
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  # --- ENTORNO NGINX ---
  nginx:
    profiles: ["nginx"]
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    restart: unless-stopped
    network_mode: service:php
    volumes:
      - ./:/var/www/html:Z
      - ./.podman/nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./certs:/etc/nginx/certs:Z
    depends_on:
      - php

  php:
    profiles: ["nginx"]
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: localhost/${PROJECT_NAME}_php_fpm:latest
    container_name: ${PROJECT_NAME}_php
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./:/var/www/html:Z

networks:
  default:
    name: ${PROJECT_NAME}_network
